<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
	<LangVersion>latest</LangVersion>
	<Nullable>enable</Nullable>
  </PropertyGroup>

	<Target Name="PostBuildCopy" AfterTargets="Build">
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ProjectDir)..\..\Mods\AliLib" />
	</Target>

	<ItemGroup>
		<Reference Include="ThunderRoad">
			<HintPath>..\..\..\Managed\ThunderRoad.dll</HintPath>
		</Reference>

		<Reference Include="UnityEngine">
			<HintPath>..\..\..\Managed\UnityEngine.dll</HintPath>
		</Reference>

		<Reference Include="UnityEngine.CoreModule">
			<HintPath>..\..\..\Managed\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
