<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
	  <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	  <Title>AliLib.Core</Title>
	  <Version>0.2.2</Version>
	  <Authors>Allieum256</Authors>
	  <Description>A Blade &amp; Sorcery Modding Library designed to promote easier, more modular scripted mods.</Description>
	  <RepositoryUrl>https://github.com/Tweety-Lab/AliLib</RepositoryUrl>
	<LangVersion>latest</LangVersion>
	<Nullable>enable</Nullable>
	<PackageIcon>icon.png</PackageIcon>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageLicenseFile>LICENSE</PackageLicenseFile>
	<GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

	<ItemGroup>
	  <None Include="..\icon.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Include="..\LICENSE">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Include="..\README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="ThunderRoad">
			<HintPath>..\..\..\Managed\ThunderRoad.dll</HintPath>
		</Reference>

		<Reference Include="UnityEngine">
			<HintPath>..\..\..\Managed\UnityEngine.dll</HintPath>
		</Reference>

		<Reference Include="UnityEngine.CoreModule">
			<HintPath>..\..\..\Managed\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
